### PR TITLE
Move OpenShift environment to stable release

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@rmohr I checked deployment with two nodes locally and it works well.

**Comment by rmohr** [comment]
hm, I find the rpm way a little bit inconvenient. Can't we simply use a reasonable git tag? What do you think?

**Comment by cynepco3hahue** [comment]
@rmohr Will check it, but as far as I know, OpenShift will move to only RPM's deployment in `3.11`, so we will need to leave `containerized` deployment anyway

**Comment by cynepco3hahue** [comment]
@rmohr I moved it back to `containerized`

**Comment by rmohr** [comment]
> @rmohr Will check it, but as far as I know, OpenShift will move to only RPM's deployment in 3.11, so we will need to leave containerized deployment anyway

Interesting. Do you have a reference at hand?

**Review by rmohr — APPROVED** [review]

**Pull request merged**
