### PR TITLE
Add --storage-opt size parameter only for devicemapper

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Overlay2 storage type dynamically increase container
root fs size.

Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
I checked it on my environment and it works as expected, can you please check it on yours?

**Review by rmohr — APPROVED** [review]
Works for me on overlay2 which does in my config not support --storage-opt

**Comment by rmohr** [comment]
@cynepco3hahue needs a rebase but works otherwise.

**Comment by cynepco3hahue** [comment]
@rmohr done

**Pull request merged**
