### PR TITLE
Update k8s image with addmission parameters

### PR DESCRIPTION
**Pull request by cynepco3hahue**

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@davidvossel FYI

**Comment by davidvossel** [comment]
i tried this new image out, it didn't appear to have the controllers enabled though

**Comment by cynepco3hahue** [comment]
Thanks for the check, I will update the image

**Comment by davidvossel** [comment]
@cynepco3hahue  aadccba01b3a32211a75a69d4ac360ea354a4a39bebfa02a9891aba206e796e8 works! thanks

**Comment by davidvossel** [comment]
https://github.com/kubevirt/kubevirt/pull/930

**Comment by davidvossel** [comment]
@cynepco3hahue I spoke too soon. This image still doesn't have the admission controllers enabled. I must have tested the wrong one earlier.

**Comment by cynepco3hahue** [comment]
@davidvossel Now it must be ok, I double checked it, sorry for delay.

**Review by davidvossel — APPROVED** [review]
the new one works

**Pull request merged**
